### ISSUE TITLE
Add parameters to 'issueVirtualCard' method 

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/gifu#151]
Input Parameters for 'issueVirtualCard' method:
<img width="657" alt="Screenshot 2022-07-11 at 14 49 51" src="https://user-images.githubusercontent.com/38030865/178257896-a59843ca-e665-44c0-9918-b7f2ca5d82a1.png">

Need to add such parameters:

```
"cardInfo":[
        {"Vendor name=AccommodationName":"VALUE_1"},
        {"Confirmation number":"VALUE_2"},
        {"Guest name":"VALUE_3"}, //Lead passenger 
        {"Check-in date":"VALUE_4"},
        {"Check-out date":"VALUE_5"},
        ]

```

**Comment by ViTsvetkova** [comment]
Guest name = lead pax name
