### ISSUE TITLE
Check and fix deleting VCC when booking cancellation [Amex]

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/gifu#212]
**AR**:  If cancel a reservation, we don't send request to delete the VCC to Amex and there is no data in logs. 

**ER**: Need to send request to delete the VCC to Amex and add information in logs.

**Comment by nikolaeva31** [comment]
https://happytravel.freshdesk.com/a/tickets/751

**Comment by DaniyarAskarov** [comment]
The problem was in a short period of time. At the moment it has been resolved.

**Comment by nikolaeva31** [comment]
Error was reproduced on dev after restarting 'gifu' service
https://logs-dev.happytravel.com/app/discover#/doc/97718760-2573-11ed-bcc8-bbc1434ea904/fluentd-gifu-2022.10?id=vYgCFoQBFWxLmY509-hb
